// reactjs/react-framework-intro/src/App.js
import React, { Component } from 'react';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom';
import './App.css';
import User from './components/User'
import Account from './components/Account'
import Blog from './components/Blog'

class App extends Component {
  render() {
    return (
        <Router>
          <div>
            <div>
              <Link to="/">Home</Link> |
              <Link to="/account">Account</Link> |
              <Link to="/blog">Blog</Link>
            </div>
            <hr/>
            <Route exact path="/" component={User}></Route>
            <Route path="/account" component={Account}></Route>
            <Route path="/blog" component={Blog}></Route>
          </div>
        </Router>
    );
  }
}

export default App;

// vuejs/vue-framework-intro/src/App.vue
<template>
  <div id="app">
    <div>
      <router-link to="/">Home</router-link>
      <router-link to="/Account">Account</router-link>
      <router-link to="/Info">Info</router-link>
      <router-link to="/Blog">Blog</router-link>
    </div>
    <router-view></router-view>
    <!-- app-user></app-user-->
    <p>This is a test.</p>
  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>
